---
Name: catalogmanager
---

Page:
  extensions:
    - LittleGiant\CatalogManager\Extensions\CategoryPageHierarchyExtension

SilverStripe\SiteConfig\SiteConfig:
  required_permission:
    - SITETREE_VIEW_ALL
    - SITETREE_EDIT_ALL

# GridField extensions configuration for SilverStripe 4
Symbiote\GridFieldExtensions\GridFieldOrderableRows:
  extensions:
    - LittleGiant\CatalogManager\Extensions\AutoPublishSortExtension

# GridField extensions configuration for SilverStripe 5
SilverStripe\Forms\GridFieldExtensions\GridFieldOrderableRows:
  extensions:
    - LittleGiant\CatalogManager\Extensions\AutoPublishSortExtension
